version: "3.9"
services:
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=licha
      - POSTGRES_PASSWORD=licha
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=licha
      - SPRING_DATASOURCE_PASSWORD=licha
    ports:
      - "8083:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./path/to/app:/app
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  postgres-data: