version: "3.9"
services:
  postgres-db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "8083:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  postgres-data:
    driver: local