version: "3.9"
services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8083:8080"
    volumes:
      - ./path/to/app:/app
    networks:
      - ecommerce-network

networks:
  ecommerce-network: