version: "3"
services:
  ecommerce-back:
    container_name: ecommerce-back
    image: ecommerce-back
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    networks:
      - ecommerce-network

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: licha
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ecommerce-network

networks:
  ecommerce-network: