version: "3"
services:
  ecommerce-back:
    container_name: ecommerce-back
    image: ecommerce-back
    build: .
    ports:
      - 8081:8080
    depends_on:
      - postgresdb
    networks:
      - ecommerce-network
networks:
  ecommerce-network: