version: '3'
services:
  mysql-db:
    image: mysql:5.7
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: licha
      MYSQL_PASSWORD: licha
      MYSQL_ROOT_PASSWORD: licha
    networks:
      - network-ecommerce

  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-app
    ports:
      - 8083:8080
    depends_on:
      - mysql-db
    networks:
      - network-ecommerce

networks:
  network-ecommerce: