services:
  - name: ecommerce-back
    image: ecommerce-back
    buildCommand: docker build -t ecommerce-back .
    startCommand: docker run -p 8081:8080 --name ecommerce-back --network ecommerce-network ecommerce-back
    ports:
      - port: 8081
        as: 8080
    dependsOn:
      - name: mysqldb

  - name: mysqldb
    image: mysql
    startCommand: docker run -p 3308:3306 --name mysqldb --network ecommerce-network -e MYSQL_DATABASE=ecommerce -e MYSQL_USER=licha -e MYSQL_PASSWORD=root -e MYSQL_ROOT_PASSWORD=root mysql
    ports:
      - port: 3308
        as: 3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: licha
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

networks:
  - name: ecommerce-network