version: render/v1
services:
  - name: ecommerce-back
    image: ecommerce-back
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    env:
      - name: MYSQL_HOST
        from_service: mysqldb
    networks:
      - ecommerce-network

  - name: mysqldb
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: licha
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ecommerce-network

networks:
  - name: ecommerce-network